name: drupalashevillelando
recipe: pantheon
config:
  framework: drupal8
  site: drupalashevillelando
  id: 831619c8-0e8a-4c49-8983-f3fcb86f865b

tooling:
  move:master:
    description: Move changes from Github to Pantheon
    service: appserver
    cmd:
      - git pull origin master
      - git push pantheon master
